server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhanslarico11/PF.git
          search-paths:
          #username:
          #password:
          default-label: ms-config-server
  security:
    user:
      name: root
      password: s3cr3t


